### ISSUE TITLE
Navbar Landing

### ISSUE THREAD

**Issue by patrigarcia** [IgrowkerTraining/i003-nativo-front#1]
Crear una barra de navegación responsiva.
Hablar con UX para saber qué secciones debe tener (Inicio, Sobre nosotros, Características, Registro, Iniciar sesión)
Implementar rutas de navegación para los links de la navbar

**Comment by Lucas-Quiroga** [comment]
PR Here https://github.com/igrowker/i003-nativo-front/pull/16

**Comment by Andrea-Laurino** [comment]
Buenas... 
Se han realizado los test y hemos encontrado bugs dejo la planilla para que los vean y pueden hacer comentario o aclaraciones en la última columna.
https://docs.google.com/spreadsheets/d/16dDX4058OPk1zweLCvH8u4BBVyTa_DTRjXsnnArnRkI/edit?gid=867971997#gid=867971997

**Comment by Andrea-Laurino** [comment]
hola Lucas! se realizó alguna modificación? porque hice el re-test y el bug sigue estando...

**Comment by Lucas-Quiroga** [comment]
Hola @Andrea-Laurino, bajaste los ultimos cambios de la rama develop? al hacer click en los links se cierra correctamente la navbar. o no entendi la referencia que pusiste en la planilla

**Comment by Andrea-Laurino** [comment]
si, lo tuve que hacer 4 veces hasta que lo pude ver... ese bug esta resuelto pero... encontre otro, te lo comento por aca y ahora lo subo a la planilla

**Comment by Andrea-Laurino** [comment]
![Image](https://github.com/user-attachments/assets/72d82377-106d-4b95-81e3-9e8f86de7f4c)

como veras no puedo ver "ayuda y Cerrar sesión" salvo que modifique el tamaño y lo haga más pequeño.

**Comment by Andrea-Laurino** [comment]
ahí ya lo agregue!.

https://docs.google.com/spreadsheets/d/16dDX4058OPk1zweLCvH8u4BBVyTa_DTRjXsnnArnRkI/edit?gid=867971997#gid=867971997
