### ISSUE TITLE
Sección Microcréditos (explicación)

### ISSUE THREAD

**Issue by sheidiz** [IgrowkerTraining/i003-nativo-front#14]
Explicación de cómo funcionan los microcréditos

Se puede ingresar a través del menú en Ayuda microcréditos con la ruta /microcredits

- Debe poder ingresar a crear un microcrédito con el botón de Gestionar microcrédito
- Debe poder ingresar a contribuir a un microcrédito con el botón de contribuir
- Debe poder ingresar a realizar una donación con el  botón donar.

**Comment by Andrea-Laurino** [comment]
Lo probamos lo único que nos surgió es este bug, BUG16. 
https://docs.google.com/spreadsheets/d/16dDX4058OPk1zweLCvH8u4BBVyTa_DTRjXsnnArnRkI/edit?gid=867971997#gid=867971997
