### ISSUE TITLE
Sección Crear un microcrédito

### ISSUE THREAD

**Issue by sheidiz** [IgrowkerTraining/i003-nativo-front#15]
- Formulario con los datos necesarios
- Espacio para campos de errores debajo de los inputs

Se puede ingresar a través de la botonera, a través de la explicación de los microcréditos por la ruta /apply-microcredit

- Debe poder ingresar a través de un input el Motivo principal del microcrédito, no debe quedar vacío y con un máximo de 50 caracteres.
- Debe poder ingresar el monto o cantidad de dinero a solicitar con un mínimo de 100 y un máximo de 500,000
- De poder ingresar la descripción o detalles de los motivos de su solicitud con un máximo de 256 caracteres
- Debe poder aceptar las políticas de privacidad y los términos y condiciones a través de checkbox
- Debe poder enviar los datos par su valoración a través del botón solicitar
- Debe poder ver el historial de sus microcréditos a través del botón de ver historial 
- Debe poder ver el historial de microcrédito y regresar a través del botón superior Página anterior

* NOTA: La funcionalidad de filtrar el orden de la lista aún no se ha trabajado.

**Comment by Andrea-Laurino** [comment]
Lo probamos lo único que nos surgió es este bug, BUG16.
https://docs.google.com/spreadsheets/d/16dDX4058OPk1zweLCvH8u4BBVyTa_DTRjXsnnArnRkI/edit?gid=867971997#gid=867971997

**Comment by Andrea-Laurino** [comment]
hago un comentario mas, cuando s¿se clickea en "ver mas" se ven los detalles pero hay un console.log con datos sencibles
