### ISSUE TITLE
Sección Inicio

### ISSUE THREAD

**Issue by patrigarcia** [IgrowkerTraining/i003-nativo-front#2]
Crear sección Hero (será lo primero que verán los usuarios al entrar)
- Título
- Subtitulo
- Imagen
- Botón de llamada a la acción

**Comment by jazminLU** [comment]
PR Here https://github.com/igrowker/i003-nativo-front/pull/10

**Comment by Andrea-Laurino** [comment]
Hola Jazmin, Como estas? 
Realice un video para que veas que cuando ya inicie sesion me sigue apareciendo la sección de iniciar sesión y registrar, una vez iniciado debería estar.

https://github.com/user-attachments/assets/a9bf6d15-f48f-4a00-9a33-6783ac41dd71

**Comment by jazminLU** [comment]
Hola Andrea! Yo realicé la pantalla de Home pero no hice ninguna conexión,
no sé cuál de los chicos realizó la conexión así que ya mañana a la mañana
me junto con ellos así lo solucionamos, en cuanto tenga novedad te informo
automáticamente porque se que estamos con los tiempos al límite, muchas
gracias por el video.
