### ISSUE TITLE
Componente Ingreso de dinero

### ISSUE THREAD

**Issue by sheidiz** [IgrowkerTraining/i003-nativo-front#23]
Si bien la pantalla de dashboard no está todavia terminada. Se puede probar el ingreso de dinero.
Simula ingresar dinero desde una cuenta externa a tu cuenta nativo.

**Comment by Andrea-Laurino** [comment]
Se puede ingresar dinero correctamente.
Te hago una aclaración, me parece que se dejó un console.log en algún lado ( console.log("Dinero agregado a la cuenta:", accountData); ) porque me sale esto por consola:

![Image](https://github.com/user-attachments/assets/2ea36828-12af-43a8-ae37-3f7e2dfc4477)
