### ISSUE TITLE
Componente Generacion QR

### ISSUE THREAD

**Issue by sheidiz** [IgrowkerTraining/i003-nativo-front#24]

**Comment by Lucas-Quiroga** [comment]
Dado que actualmente estoy trabajando en la pantalla de escaneo, puedes visualizar la pantalla de "¡Felicitaciones! El cobro fue exitoso" modificando la siguiente línea de código en el componente `QRGenerator.tsx` de `const [success] = useState(false)` a `const [success] = useState(true)`.
