### ISSUE TITLE
Componente Historial de todas las transacciones + filtro por status y fecha

### ISSUE THREAD

**Issue by sheidiz** [IgrowkerTraining/i003-nativo-front#38]
Creación de la página de Historial de Todos los movimientos, que se accede por /history

- Debe permitir ver todos los movimientos con sus detalles correspondientes: tipo, descripcion, fecha, hora, monto.
- Debe permitir filtrar por status (Aceptado, Pendiente, Expirado, Fallido, Completado).
- Debe permitir filtrar por fechas (Hoy, Ayer, Última semana, Últimos 15 días, Último mes, Último año). Las fechas que toma en consideración son las de la ultima edición del movimiento. Por ejemplo si la solicitud de donacion se hizo ayer, pero recien hoy se aprobo, se mostrara la fecha de hoy.

-----------

**Otros detalles**
Se accede desde:
- Dentro del dashboard se muestra una preview de los últimos 5 movimientos de la cuenta, debajo se ve un link para Ver más.
- Navbar Mis Movimientos
- Footer Mis Movimientos

Los filtros son exclusivos, o se filtra por status o por fechas, no ambos. (por como está armado en la api)

**Comment by sheidiz** [comment]
Buenas @Andrea-Laurino @elianaspaccavento ! Como va?
El historial lo revise un par de veces cuando lo estuve armando, pero se los paso por aca por si ven algún error que tal vez no note, o si les parece necesario algún ajuste estético (ya que esta pantalla fue creada solo desde front, no está en el figma).
Tanto esta tarjeta como la de donación son muy parecidas.
Si quedo algo para ajustar lo puedo tomar mañana, y si lo ven ok lo podemos ya pasar a done 😊

**Comment by Andrea-Laurino** [comment]
hola @sheidiz!! el filtro anda bien pero quisimos escribir en la barra de búsqueda y no pudimos, esta de vista o tiene funcionalidad??
 También queríamos que modifiquen el "volver al dashboard" para que este en español.

https://docs.google.com/spreadsheets/d/16dDX4058OPk1zweLCvH8u4BBVyTa_DTRjXsnnArnRkI/edit?gid=867971997#gid=867971997

**Comment by sheidiz** [comment]
Hola @Andrea-Laurino !
Ya cambie el _Volver al dashboard_ por _Volver al Inicio_. Y lo de la barra de búsqueda es a modo vista (no tenemos un endpoint que realice esa petición). Lo agregue porque quedaba medio feo dejar el botón de filtros solo, y queda a modo que se podría implementar luego
