### ISSUE TITLE
Componente donación 1 a 1

### ISSUE THREAD

**Issue by sheidiz** [IgrowkerTraining/i003-nativo-front#39]
Con la sesión iniciada, desde la botonera se puede generar una donación a otra cuenta:

EJEMPLO
Información del usuario utilizado para realizar la donación :
> email: sheila@gmail.com
> contraseña: Abcd1234!
> accountId: 6f4e3ceb-02ef-4a6f-814a-c1f656f3f4b1
> accountNumber: 12123123 (igual al dni ingresado)

Usuario utilizado para la prueba:
> email: guillermodivan@hotmail.com
> contraseña: Abcd1234!
> accountId: 6f4e3ceb-02ef-4a6f-814a-c1f656f3f4b1
> accountNumber: 36000001 (igual al dni ingresado)

Para generar una donación se debe ingresar un accountNumber y un monto mayor a $100.
En caso de que el usuario no exista, lo indicara con un mensaje de error.
No permite el ingreso de valores menores a $100.
No permite que se intente donar a si mismo.

**Comment by Andrea-Laurino** [comment]
hola shei!! que debo colocar en el input de "para"? nombre mail

**Comment by sheidiz** [comment]
Hola @Andrea-Laurino ! Como va?
Ahi ya te deje más descripción en la tarjeta.

En cuanto a las donaciones cuando se crea una solicitud de donación queda ese dinero congelado en la cuenta del usuario, teniendo asi un saldo y saldo congelado. Por eso quería preguntarles si les parece mejor
1. En el dashboard mostrar el saldo (descontando el congelado), y abajo el congelado en un color más gris.
2. En el dashboard mostrar el saldo ya descontando el congelado, y no indicar el monto congelado
Porque sino queda medio raro que al generar una solicitud de donación no cambie el monto que se ve en el dashboard.

Como no estaba en el figma, les consulto para saber si les parece avanzar con alguna de esas opciones, o tienen otra sugerencia

Edit: También ajuste lo del footer, le puse una sombrita al logo

**Comment by Andrea-Laurino** [comment]
buenisimo!! ahi paso el test!!
me encanto lo del footer.
