### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by patrigarcia** [IgrowkerTraining/i003-nativo-front#4]
Crear un footer que sea informativo, estéticamente consistente con el diseño general del sitio web de Nativo Banco Rural.

Contacto
Politica de privacidad
Aviso legal
Soporte
Colocar texto de derechos de autor indicando el año y el nombre de la empresa, por ejemplo, "© 2024 Nativo Banco Rural".

**Comment by MaJoGR1** [comment]
Footer listo en Figma. En Assets dejé la grilla de destop que estaremos usando: 12 columnas, margen de 80px, calles de 20px

**Comment by andresfernandez89** [comment]
> Footer listo en Figma. En Assets dejé la grilla de destop que estaremos usando: 12 columnas, margen de 80px, calles de 20px

Muchas gracias.
Consulta, el componente de "Descarga de la app". Esa funcionalidad no la vamos a hacer, ya que no es una app movil nativa, sin una webapp.

**Comment by Andrea-Laurino** [comment]
hola @sheidiz , quiero hacerte una comentario para mejorar la IU, podra ser posible que una vez iniciada sesión, el footer no incluya "iniciar Sesión" ni "Registró" ya que seria innecesario que esten.... Si te la complico no le des importancia...

**Comment by sheidiz** [comment]
> hola [@sheidiz](https://github.com/sheidiz) , quiero hacerte una comentario para mejorar la IU, podra ser posible que una vez iniciada sesión, el footer no incluya "iniciar Sesión" ni "Registró" ya que seria innecesario que esten.... Si te la complico no le des importancia...

Buenas @Andrea-Laurino !
Sisi lo tenia contemplado, por eso lo deje aca In Progress, estaba esperando que Lucas suba la navbar (que hace esto) para replicarlo en el footer. Gracias por mencionar el detalle de todas formas 🙌

**Comment by Andrea-Laurino** [comment]
hola Shei! 
tardó pero se me actualizo el repo... ahi vi los cambios!! muchas gracias!
