### ISSUE TITLE
Componente Historial de mis donaciones + aprobar donaciones recibidas

### ISSUE THREAD

**Issue by sheidiz** [IgrowkerTraining/i003-nativo-front#42]
Creación de la página de Historial de las Todos las donaciones, que se accede por /donations.

- Debe permitir ver todas las donaciones con sus detalles correspondientes: tipo, descripcion, fecha, hora, monto.
- Debe permitir filtrar por status (Aceptado, Pendiente, Expirado, Fallido, Completado).
- Debe permitir filtrar por fechas (Hoy, Ayer, Última semana, Últimos 15 días, Último mes, Último año). Las fechas que toma en consideración son las de la ultima edición del movimiento. Por ejemplo si la solicitud de donacion se hizo ayer, pero recien hoy se aprobo, se mostrara la fecha de hoy.
- En caso de tener solicitudes de donaciones, permite aceptarlas o denegarlas.

**Otros detalles**
Se accede desde:
- Para acceder al historial de donaciones hay que ir a la navbar y a Donaciones recibidas.

**Comment by Andrea-Laurino** [comment]
La aprobación de las donaciones y filtrado andan perfecto!
