### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by patrigarcia** [IgrowkerTraining/i003-nativo-front#5]
Crear formulario para registrarse con correo electrónico y contraseña.
Incluir botones para enviar el formulario y links a términos de uso y política de privacidad. (por ser un banco).
Link a "Ya tienes cuenta?"

**Comment by Lucas-Quiroga** [comment]
PR Here https://github.com/igrowker/i003-nativo-front/pull/16

**Comment by Andrea-Laurino** [comment]
Hola chicos se encontraron 2 bugs, dejo la planilla: https://docs.google.com/spreadsheets/d/16dDX4058OPk1zweLCvH8u4BBVyTa_DTRjXsnnArnRkI/edit?gid=867971997#gid=867971997

**Comment by Lucas-Quiroga** [comment]
solucionado los 2 bugs de la planilla!
