### ISSUE TITLE
Componente vista principal (dashboard)

### ISSUE THREAD

**Issue by patrigarcia** [IgrowkerTraining/i003-nativo-front#7]
Crear una vista general que los usuarios ven al iniciar sesión, mostrando un resumen de su cuenta, saldo actual, y accesos rápidos a funciones comunes.
- Resumen de saldo
- Acceso directo a pago
- Lista de últimas transacciones ordenada por fecha

----
Comentarios:
- Se accede desde /dashboard.
- Contiene resumen de saldo, ultimas transacciones (5 para que no quede muy extenso) y una botonera con acciones.
- De las acciones de botonera se aprobo el ingreso de dinero. Las demas están todavia en trabajo

**Comment by Andrea-Laurino** [comment]
hola shei! esta precioso el dash!
